version: '3.9'

services:
  db:
    image: postgres:16
    container_name: aitplacement-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: aitplacement
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
