// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePost(ctx context.Context, arg *CreatePostParams) (*Post, error)
	DeletePostById(ctx context.Context, id pgtype.UUID) error
	GetPostById(ctx context.Context, id pgtype.UUID) (*Post, error)
	ListAllPosts(ctx context.Context) ([]*ListAllPostsRow, error)
	UpdatePost(ctx context.Context, arg *UpdatePostParams) (*Post, error)
}

var _ Querier = (*Queries)(nil)
